# Generated by Django 5.1.3 on 2024-12-12 11:52

import datetime
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('confirmpassword', models.CharField(max_length=8)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=datetime.datetime(2024, 12, 12, 17, 22, 44, 306196))),
                ('date_birth', models.DateField(default=django.utils.timezone.now)),
                ('Photo', models.ImageField(upload_to='')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttrakhand', 'Uttrakhand'), ('Uttara Pradesh', 'Uttara Pradesh'), ('West Bengal', 'West Bengal')], max_length=17)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Femal', 'Femal'), ('Other', 'Other')], max_length=5)),
            ],
        ),
    ]
