# Generated by Django 5.1.3 on 2024-12-12 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Photo',
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 12, 17, 37, 6, 712651)),
        ),
    ]
