# Generated by Django 5.1.3 on 2024-12-13 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_student_photo_alter_student_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 13, 10, 7, 52, 507082)),
        ),
    ]
