# Generated by Django 5.1.3 on 2024-12-13 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_student_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 13, 10, 20, 31, 932849)),
        ),
    ]
